template = "https://github.com/giellalt/template-lang-und"
rev_id = 281
template_sha = "818353eecbfc8e1309992f6739dfde72a0afbec0"

[replacements]
__GLOTTOLOG_ID__ = "rusy1239"
__LICENCE__ = "GPLv3"
__REPO__ = "lang-rue"
__UND2C__ = "rue"
__UNDEFINED__ = "Rusyn"
__UND__ = "rue"
