template = ""
rev_id = 198
template_sha = "c528583032290536023c7e6a65d4f1a65dcb0d30"

[replacements]
__LICENCE__ = "GPLv3"
__REPO__ = "lang-rue"
__UND2C__ = "rue"
__UNDEFINED__ = "Rusyn"
__UND__ = "rue"
