template = "https://github.com/giellalt/template-lang-und"
rev_id = 253
template_sha = "5e69b0634aa0bd9773dece52e5b15d3003d605f1"

[replacements]
__GLOTTOLOG_ID__ = "rusy1239"
__LICENCE__ = "GPLv3"
__REPO__ = "lang-rue"
__UND2C__ = "rue"
__UNDEFINED__ = "Rusyn"
__UND__ = "rue"
