template = "https://github.com/giellalt/template-lang-und"
rev_id = 278
template_sha = "58c9d1b66bc21da4ce588378206dd02d219954ae"

[replacements]
__GLOTTOLOG_ID__ = "rusy1239"
__LICENCE__ = "GPLv3"
__REPO__ = "lang-rue"
__UND2C__ = "rue"
__UNDEFINED__ = "Rusyn"
__UND__ = "rue"
