template = ""
rev_id = 192
template_sha = "02ff4d9dc4e819c21ed53241bd49228e7a3c5dfd"

[replacements]
__LICENCE__ = "GPLv3"
__REPO__ = "lang-rue"
__UND2C__ = "rue"
__UNDEFINED__ = "Rusyn"
__UND__ = "rue"
